// Code generated by "stringer -type engineEvent --linecomment"; DO NOT EDIT.

package conch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[engineEventSuccess-0]
	_ = x[engineEventFailure-1]
	_ = x[engineEventRefresh-2]
}

const _engineEvent_name = "EVT_SUCCESSEVT_FAILUREEVT_REFRESH"

var _engineEvent_index = [...]uint8{0, 11, 22, 33}

func (i engineEvent) String() string {
	if i >= engineEvent(len(_engineEvent_index)-1) {
		return "engineEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _engineEvent_name[_engineEvent_index[i]:_engineEvent_index[i+1]]
}
