// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockIndexGetter is an autogenerated mock type for the IndexGetter type
type MockIndexGetter[O interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockIndexGetter[O]) Execute(_a0 O) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(O) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewMockIndexGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIndexGetter creates a new instance of MockIndexGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIndexGetter[O interface{}](t mockConstructorTestingTNewMockIndexGetter) *MockIndexGetter[O] {
	mock := &MockIndexGetter[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
