// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockOrdered is an autogenerated mock type for the Ordered type
type MockOrdered struct {
	mock.Mock
}

type mockConstructorTestingTNewMockOrdered interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOrdered creates a new instance of MockOrdered. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOrdered(t mockConstructorTestingTNewMockOrdered) *MockOrdered {
	mock := &MockOrdered{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
