// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockUnsigned is an autogenerated mock type for the Unsigned type
type MockUnsigned struct {
	mock.Mock
}

type MockUnsigned_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsigned) EXPECT() *MockUnsigned_Expecter {
	return &MockUnsigned_Expecter{mock: &_m.Mock}
}

// NewMockUnsigned creates a new instance of MockUnsigned. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsigned(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsigned {
	mock := &MockUnsigned{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
