// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockFloat is an autogenerated mock type for the Float type
type MockFloat struct {
	mock.Mock
}

type MockFloat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFloat) EXPECT() *MockFloat_Expecter {
	return &MockFloat_Expecter{mock: &_m.Mock}
}

// NewMockFloat creates a new instance of MockFloat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFloat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFloat {
	mock := &MockFloat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
