// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockValErrorPairProvider is an autogenerated mock type for the ValErrorPairProvider type
type MockValErrorPairProvider[R interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *MockValErrorPairProvider[R]) Execute(ctx context.Context) ValErrorPair[R] {
	ret := _m.Called(ctx)

	var r0 ValErrorPair[R]
	if rf, ok := ret.Get(0).(func(context.Context) ValErrorPair[R]); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(ValErrorPair[R])
	}

	return r0
}

type mockConstructorTestingTNewMockValErrorPairProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockValErrorPairProvider creates a new instance of MockValErrorPairProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockValErrorPairProvider[R interface{}](t mockConstructorTestingTNewMockValErrorPairProvider) *MockValErrorPairProvider[R] {
	mock := &MockValErrorPairProvider[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
