// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockSigned is an autogenerated mock type for the Signed type
type MockSigned struct {
	mock.Mock
}

type mockConstructorTestingTNewMockSigned interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSigned creates a new instance of MockSigned. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSigned(t mockConstructorTestingTNewMockSigned) *MockSigned {
	mock := &MockSigned{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
