// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockDoer[T]) Execute(_a0 context.Context, _a1 T) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewMockDoer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDoer[T interface{}](t mockConstructorTestingTNewMockDoer) *MockDoer[T] {
	mock := &MockDoer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
