// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockComplex is an autogenerated mock type for the Complex type
type MockComplex struct {
	mock.Mock
}

type MockComplex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplex) EXPECT() *MockComplex_Expecter {
	return &MockComplex_Expecter{mock: &_m.Mock}
}

// NewMockComplex creates a new instance of MockComplex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplex {
	mock := &MockComplex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
