// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockInteger is an autogenerated mock type for the Integer type
type MockInteger struct {
	mock.Mock
}

type mockConstructorTestingTNewMockInteger interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockInteger creates a new instance of MockInteger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockInteger(t mockConstructorTestingTNewMockInteger) *MockInteger {
	mock := &MockInteger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
