// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockBreakerEngine is an autogenerated mock type for the BreakerEngine type
type MockBreakerEngine struct {
	mock.Mock
}

// IsOpen provides a mock function with given fields:
func (_m *MockBreakerEngine) IsOpen() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ReportFailure provides a mock function with given fields:
func (_m *MockBreakerEngine) ReportFailure() {
	_m.Called()
}

// ReportSuccess provides a mock function with given fields:
func (_m *MockBreakerEngine) ReportSuccess() {
	_m.Called()
}

type mockConstructorTestingTNewMockBreakerEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBreakerEngine creates a new instance of MockBreakerEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBreakerEngine(t mockConstructorTestingTNewMockBreakerEngine) *MockBreakerEngine {
	mock := &MockBreakerEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
