// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc[T interface{}] struct {
	mock.Mock
}

type MockFilterFunc_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockFilterFunc[T]) EXPECT() *MockFilterFunc_Expecter[T] {
	return &MockFilterFunc_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, v
func (_m *MockFilterFunc[T]) Execute(ctx context.Context, v T) bool {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, T) bool); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFilterFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilterFunc_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - v T
func (_e *MockFilterFunc_Expecter[T]) Execute(ctx interface{}, v interface{}) *MockFilterFunc_Execute_Call[T] {
	return &MockFilterFunc_Execute_Call[T]{Call: _e.mock.On("Execute", ctx, v)}
}

func (_c *MockFilterFunc_Execute_Call[T]) Run(run func(ctx context.Context, v T)) *MockFilterFunc_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockFilterFunc_Execute_Call[T]) Return(_a0 bool) *MockFilterFunc_Execute_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilterFunc_Execute_Call[T]) RunAndReturn(run func(context.Context, T) bool) *MockFilterFunc_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockFilterFunc creates a new instance of MockFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterFunc[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterFunc[T] {
	mock := &MockFilterFunc[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
