// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator[T interface{}] struct {
	mock.Mock
}

type MockGenerator_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockGenerator[T]) EXPECT() *MockGenerator_Expecter[T] {
	return &MockGenerator_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockGenerator[T]) Execute(ctx context.Context) (<-chan T, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan T, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan T); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGenerator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGenerator_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGenerator_Expecter[T]) Execute(ctx interface{}) *MockGenerator_Execute_Call[T] {
	return &MockGenerator_Execute_Call[T]{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockGenerator_Execute_Call[T]) Run(run func(ctx context.Context)) *MockGenerator_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGenerator_Execute_Call[T]) Return(output <-chan T, err error) *MockGenerator_Execute_Call[T] {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockGenerator_Execute_Call[T]) RunAndReturn(run func(context.Context) (<-chan T, error)) *MockGenerator_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator[T] {
	mock := &MockGenerator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
