// Code generated by mockery v2.26.0. DO NOT EDIT.

package conch

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer[T interface{}] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, id, param
func (_m *MockDoer[T]) Execute(ctx context.Context, id int, param T) {
	_m.Called(ctx, id, param)
}

type mockConstructorTestingTNewMockDoer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDoer[T interface{}](t mockConstructorTestingTNewMockDoer) *MockDoer[T] {
	mock := &MockDoer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
