// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockSigned is an autogenerated mock type for the Signed type
type MockSigned struct {
	mock.Mock
}

type MockSigned_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSigned) EXPECT() *MockSigned_Expecter {
	return &MockSigned_Expecter{mock: &_m.Mock}
}

// NewMockSigned creates a new instance of MockSigned. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSigned(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSigned {
	mock := &MockSigned{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
