// Code generated by mockery v2.40.1. DO NOT EDIT.

package conch

import mock "github.com/stretchr/testify/mock"

// MockOrdered is an autogenerated mock type for the Ordered type
type MockOrdered struct {
	mock.Mock
}

type MockOrdered_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdered) EXPECT() *MockOrdered_Expecter {
	return &MockOrdered_Expecter{mock: &_m.Mock}
}

// NewMockOrdered creates a new instance of MockOrdered. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdered(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdered {
	mock := &MockOrdered{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
